### ISSUE TITLE
File patching no way to determine version

### ISSUE THREAD

**Issue by jonpas** [BrettMayson/HEMTT#302] opened 2020-03-17 09:15 UTC
**HEMTT Version:** `0.8.0` (dev d828af84613f6725732a4c42c8b4611ae2a0cf81)
**Project:** https://github.com/CBATeam/CBA_A3/pull/1145

**Description:**

`$ hemtt file-patching` errors with "No way to determine the version number was detected". Building it works just fine.

**Steps to reproduce:**

- Run `$ hemtt file-patching`

**Additional information:**

Why would file-patching even care about version? :P

**HEMTT Output:**

```
E:\Arma 3\Mods\CBA_A3>hemtt.exe file-patching
HEMTT 0.8.0-d828af84613f6725732a4c42c8b4611ae2a0cf81-d828af8
Environment: dev

error: No way to determine the version number was detected
    Use `cmd /C "set APP_VERSION={} && hemtt ..."` to specify a version for this build
```

**Comment by synixebrett** [comment] 2020-04-02 16:24
It wants the version number because it needs the project information, and the project struct has to have a version.

I was unable to reproduce this, the projects I had worked fine for file-patching if they could also be built, more information may be required.

**Comment by jonpas** [comment] 2020-04-02 16:37
Happens with CBA (current master HEMTT) on my machine.

**Comment by synixebrett** [comment] 2020-05-05 17:08
I am able to replicate with CBA, need to figure out why CBA is an edge case here as it looks like it should work fine

**Comment by BrettMayson** [comment] 2023-01-23 23:26
Closing, should be fixed with 0,10

**Closed by BrettMayson** 2023-01-23 23:26 UTC
Labels: bug, need info
