### ISSUE TITLE
Feature Request - Directory-related call access within rhai scripts

### ISSUE THREAD

**Issue by nojusr** [BrettMayson/HEMTT#519] opened 2023-06-08 15:05 UTC
I'm trying to write a rhai script that would copy a folder of files into a specific space into the `.hemttout/build` folder, in a `post-build` hook, within the VFS. The passed functions from rust into rhai within the vfs path module don't seem to have `read_dir` and/or `open_dir` included.

**Comment by BrettMayson** [comment] 2023-06-21 00:50
You can copy a directory currently, I will look into an iterator over files in a future version.

**Comment by BrettMayson** [comment] 2023-11-02 09:46
Duplicate of https://github.com/BrettMayson/HEMTT/discussions/589

**Closed by BrettMayson** 2023-11-02 09:46 UTC
Labels: enhancement
