### ISSUE TITLE
Building addons is caped around 200 MB

### ISSUE THREAD

**Issue by Katalam** [BrettMayson/HEMTT#125] opened 2019-06-06 23:51 UTC
**HEMTT Version:** `0.6.1` (not sure I'll taked the ci method from Brett)

**Description:**
I tried to convert my CBA Project Building to the HEMTT system.
When I try to execute ```.\hemtt build --release``` it fails with the sentence: ```memory allocation of 1610612736 bytes failed```. The pbo is a music folder with around 250 MB. I removed the folder and everything worked fine. I think a 250 MB cap is quite small. But I am not sure if this is a coded cap.

**Steps to reproduce:**

- The music is not on my github but you can use your own music
- [GitHub Link](https://github.com/Katalam/kat_10thmods/tree/hemtt) from the rest of the project

**Comment by synixebrett** [comment] 2019-06-07 01:21
Please provide the full output, this will help us determine where in the program the issue is occurring.

**Comment by synixebrett** [comment] 2019-09-27 21:19
This is a bug with Armake2, I think this is being caused by the lack of available memory. This is a result of how Armake2 handles PBOs. The entire thing needs to fit in RAM. You can try using `-j 1` to only build one PBO at a time to keep more memory available.

**Comment by BrettMayson** [comment] 2023-03-04 22:17
This should be fixed in v0.10

**Closed by BrettMayson** 2023-03-04 22:17 UTC
Labels: bug, external
